//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Car
    {
        public Car()
        {
            this.RepairCards = new HashSet<RepairCard>();
        }
    
        public int Id { get; set; }
        [Required]
        public string RegistryNumber { get; set; }
        [Required]
        public string Brand { get; set; }
        [Required]
        public string Model { get; set; }
        [Required]
        public int Year { get; set; }
        [Required]
        public int FrameNumber { get; set; }
        [Required]
        public int EngineNumber { get; set; }
        [Required]
        public string Color { get; set; }
        [Required]
        public int EngineWorkVolume { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Owner { get; set; }
        [Required]
        public int PhoneNumber { get; set; }
        [Required]
        public int UserId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<RepairCard> RepairCards { get; set; }
    }
}
